// Mocks generated by Mockito 5.4.5 from annotations
// in dima_project/test/provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i10;

import 'package:dima_project/content/bookings/booking_model.dart' as _i5;
import 'package:dima_project/content/bookings/booking_update_model.dart' as _i9;
import 'package:dima_project/content/bookings/bookings_provider.dart' as _i3;
import 'package:dima_project/content/home/gym/activity/activity_model.dart'
    as _i7;
import 'package:dima_project/content/home/gym/activity/book_slot/slot_model.dart'
    as _i8;
import 'package:dima_project/content/home/gym/activity/book_slot/slot_provider.dart'
    as _i18;
import 'package:dima_project/content/home/gym/gym_model.dart' as _i6;
import 'package:dima_project/content/instructors/instructor_model.dart' as _i17;
import 'package:dima_project/content/instructors/instructor_provider.dart'
    as _i16;
import 'package:dima_project/global_providers/gym_provider.dart' as _i14;
import 'package:dima_project/global_providers/screen_provider.dart' as _i11;
import 'package:dima_project/global_providers/user/user_model.dart' as _i13;
import 'package:dima_project/global_providers/user/user_provider.dart' as _i12;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMediaQueryData_0 extends _i1.SmartFake
    implements _i2.MediaQueryData {
  _FakeMediaQueryData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BookingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookingsProvider extends _i1.Mock implements _i3.BookingsProvider {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<List<_i5.Booking>> getTodaysBookings() =>
      (super.noSuchMethod(
            Invocation.method(#getTodaysBookings, []),
            returnValue: _i4.Future<List<_i5.Booking>>.value(<_i5.Booking>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.Booking>>.value(
              <_i5.Booking>[],
            ),
          )
          as _i4.Future<List<_i5.Booking>>);

  @override
  _i4.Future<List<_i5.Booking>?> getBookings() =>
      (super.noSuchMethod(
            Invocation.method(#getBookings, []),
            returnValue: _i4.Future<List<_i5.Booking>?>.value(),
            returnValueForMissingStub: _i4.Future<List<_i5.Booking>?>.value(),
          )
          as _i4.Future<List<_i5.Booking>?>);

  @override
  _i4.Future<bool> createBooking(
    _i6.Gym? gym,
    _i7.Activity? activity,
    _i8.Slot? slot,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createBooking, [gym, activity, slot]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> removeBooking(_i5.Booking? booking) =>
      (super.noSuchMethod(
            Invocation.method(#removeBooking, [booking]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  int getBookingIndex(String? bookingId) =>
      (super.noSuchMethod(
            Invocation.method(#getBookingIndex, [bookingId]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void addToCalendar(_i5.Booking? booking) => super.noSuchMethod(
    Invocation.method(#addToCalendar, [booking]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<List<_i9.BookingUpdate>> getBookingUpdates() =>
      (super.noSuchMethod(
            Invocation.method(#getBookingUpdates, []),
            returnValue: _i4.Future<List<_i9.BookingUpdate>>.value(
              <_i9.BookingUpdate>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i9.BookingUpdate>>.value(
                  <_i9.BookingUpdate>[],
                ),
          )
          as _i4.Future<List<_i9.BookingUpdate>>);

  @override
  _i4.Future<void> markUpdateAsRead(_i9.BookingUpdate? bookingUpdate) =>
      (super.noSuchMethod(
            Invocation.method(#markUpdateAsRead, [bookingUpdate]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ScreenProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockScreenProvider extends _i1.Mock implements _i11.ScreenProvider {
  @override
  _i2.MediaQueryData get screenData =>
      (super.noSuchMethod(
            Invocation.getter(#screenData),
            returnValue: _FakeMediaQueryData_0(
              this,
              Invocation.getter(#screenData),
            ),
            returnValueForMissingStub: _FakeMediaQueryData_0(
              this,
              Invocation.getter(#screenData),
            ),
          )
          as _i2.MediaQueryData);

  @override
  bool get useMobileLayout =>
      (super.noSuchMethod(
            Invocation.getter(#useMobileLayout),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set screenData(_i2.MediaQueryData? mqd) => super.noSuchMethod(
    Invocation.setter(#screenData, mqd),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProvider extends _i1.Mock implements _i12.UserProvider {
  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAdmin =>
      (super.noSuchMethod(
            Invocation.getter(#isAdmin),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<_i13.User?> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i4.Future<_i13.User?>.value(),
            returnValueForMissingStub: _i4.Future<_i13.User?>.value(),
          )
          as _i4.Future<_i13.User?>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i13.User?> fetchUser() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUser, []),
            returnValue: _i4.Future<_i13.User?>.value(),
            returnValueForMissingStub: _i4.Future<_i13.User?>.value(),
          )
          as _i4.Future<_i13.User?>);

  @override
  _i4.Future<List<_i13.User>> getUsersByIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByIds, [ids]),
            returnValue: _i4.Future<List<_i13.User>>.value(<_i13.User>[]),
            returnValueForMissingStub: _i4.Future<List<_i13.User>>.value(
              <_i13.User>[],
            ),
          )
          as _i4.Future<List<_i13.User>>);

  @override
  _i4.Future<void> addFavouriteGym(String? gymId) =>
      (super.noSuchMethod(
            Invocation.method(#addFavouriteGym, [gymId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFavouriteGym(String? gymId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavouriteGym, [gymId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GymProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGymProvider extends _i1.Mock implements _i14.GymProvider {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<List<_i6.Gym>> getGymList() =>
      (super.noSuchMethod(
            Invocation.method(#getGymList, []),
            returnValue: _i4.Future<List<_i6.Gym>>.value(<_i6.Gym>[]),
            returnValueForMissingStub: _i4.Future<List<_i6.Gym>>.value(
              <_i6.Gym>[],
            ),
          )
          as _i4.Future<List<_i6.Gym>>);

  @override
  _i4.Future<void> addGym(_i6.Gym? gym) =>
      (super.noSuchMethod(
            Invocation.method(#addGym, [gym]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateGym(_i6.Gym? gym) =>
      (super.noSuchMethod(
            Invocation.method(#updateGym, [gym]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeGym(_i6.Gym? gym) =>
      (super.noSuchMethod(
            Invocation.method(#removeGym, [gym]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addActivity(_i6.Gym? gym, _i7.Activity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#addActivity, [gym, activity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateActivity(_i6.Gym? gym, _i7.Activity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#updateActivity, [gym, activity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeActivity(_i6.Gym? gym, _i7.Activity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#removeActivity, [gym, activity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  int getGymIndex(_i6.Gym? gym) =>
      (super.noSuchMethod(
            Invocation.method(#getGymIndex, [gym]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i4.Future<String> uploadImage(String? base64Image) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [base64Image]),
            returnValue: _i4.Future<String>.value(
              _i15.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [base64Image]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i15.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [base64Image]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [InstructorProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockInstructorProvider extends _i1.Mock
    implements _i16.InstructorProvider {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<List<_i17.Instructor>?> getInstructorList() =>
      (super.noSuchMethod(
            Invocation.method(#getInstructorList, []),
            returnValue: _i4.Future<List<_i17.Instructor>?>.value(),
            returnValueForMissingStub:
                _i4.Future<List<_i17.Instructor>?>.value(),
          )
          as _i4.Future<List<_i17.Instructor>?>);

  @override
  _i4.Future<void> deleteInstructor(_i17.Instructor? instructor) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInstructor, [instructor]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> addInstructor(_i17.Instructor? instructor) =>
      (super.noSuchMethod(
            Invocation.method(#addInstructor, [instructor]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SlotProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSlotProvider extends _i1.Mock implements _i18.SlotProvider {
  @override
  String get gymId =>
      (super.noSuchMethod(
            Invocation.getter(#gymId),
            returnValue: _i15.dummyValue<String>(
              this,
              Invocation.getter(#gymId),
            ),
            returnValueForMissingStub: _i15.dummyValue<String>(
              this,
              Invocation.getter(#gymId),
            ),
          )
          as String);

  @override
  String get activityId =>
      (super.noSuchMethod(
            Invocation.getter(#activityId),
            returnValue: _i15.dummyValue<String>(
              this,
              Invocation.getter(#activityId),
            ),
            returnValueForMissingStub: _i15.dummyValue<String>(
              this,
              Invocation.getter(#activityId),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<List<_i8.Slot>> getUpcomingSlots() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingSlots, []),
            returnValue: _i4.Future<List<_i8.Slot>>.value(<_i8.Slot>[]),
            returnValueForMissingStub: _i4.Future<List<_i8.Slot>>.value(
              <_i8.Slot>[],
            ),
          )
          as _i4.Future<List<_i8.Slot>>);

  @override
  _i4.Future<void> createSlot(
    _i8.Slot? slot,
    String? recurrence,
    DateTime? until,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSlot, [slot, recurrence, until]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateSlot(_i8.Slot? slot) =>
      (super.noSuchMethod(
            Invocation.method(#updateSlot, [slot]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addUserToSlot(String? slotId) =>
      (super.noSuchMethod(
            Invocation.method(#addUserToSlot, [slotId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSlot(String? slotId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSlot, [slotId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
