// Mocks generated by Mockito 5.4.5 from annotations
// in gymme/test/service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i21;
import 'dart:typed_data' as _i22;

import 'package:add_2_calendar/add_2_calendar.dart' as _i11;
import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:geolocator/geolocator.dart' as _i24;
import 'package:gymme/content/map/map_service.dart' as _i23;
import 'package:gymme/models/activity_model.dart' as _i15;
import 'package:gymme/models/booking_model.dart' as _i8;
import 'package:gymme/models/booking_update_model.dart' as _i10;
import 'package:gymme/models/gym_model.dart' as _i13;
import 'package:gymme/models/instructor_model.dart' as _i19;
import 'package:gymme/models/location_model.dart' as _i5;
import 'package:gymme/models/slot_model.dart' as _i9;
import 'package:gymme/models/user_model.dart' as _i17;
import 'package:gymme/services/bookings_service.dart' as _i6;
import 'package:gymme/services/gym_service.dart' as _i12;
import 'package:gymme/services/instructor_service.dart' as _i18;
import 'package:gymme/services/slot_service.dart' as _i20;
import 'package:gymme/services/user_service.dart' as _i16;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseAuth_1 extends _i1.SmartFake implements _i3.FirebaseAuth {
  _FakeFirebaseAuth_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_3 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocations_4 extends _i1.SmartFake implements _i5.Locations {
  _FakeLocations_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BookingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookingsService extends _i1.Mock implements _i6.BookingsService {
  @override
  _i2.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
            returnValueForMissingStub: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i2.FirebaseFirestore);

  @override
  _i3.FirebaseAuth get firebaseAuth =>
      (super.noSuchMethod(
            Invocation.getter(#firebaseAuth),
            returnValue: _FakeFirebaseAuth_1(
              this,
              Invocation.getter(#firebaseAuth),
            ),
            returnValueForMissingStub: _FakeFirebaseAuth_1(
              this,
              Invocation.getter(#firebaseAuth),
            ),
          )
          as _i3.FirebaseAuth);

  @override
  _i7.Future<List<_i8.Booking>> fetchBookings() =>
      (super.noSuchMethod(
            Invocation.method(#fetchBookings, []),
            returnValue: _i7.Future<List<_i8.Booking>>.value(<_i8.Booking>[]),
            returnValueForMissingStub: _i7.Future<List<_i8.Booking>>.value(
              <_i8.Booking>[],
            ),
          )
          as _i7.Future<List<_i8.Booking>>);

  @override
  _i7.Future<String?> addBooking(_i8.Booking? booking, _i9.Slot? slot) =>
      (super.noSuchMethod(
            Invocation.method(#addBooking, [booking, slot]),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> deleteBooking(_i8.Booking? booking) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBooking, [booking]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> markUpdateAsRead(_i10.BookingUpdate? bookingUpdate) =>
      (super.noSuchMethod(
            Invocation.method(#markUpdateAsRead, [bookingUpdate]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addToCalendarWeb(String? url) => super.noSuchMethod(
    Invocation.method(#addToCalendarWeb, [url]),
    returnValueForMissingStub: null,
  );

  @override
  void addToCalendarMobile(_i11.Event? event) => super.noSuchMethod(
    Invocation.method(#addToCalendarMobile, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> goToPayment(_i8.Booking? booking) =>
      (super.noSuchMethod(
            Invocation.method(#goToPayment, [booking]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> confirmPayment(String? bookingId) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPayment, [bookingId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [GymService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGymService extends _i1.Mock implements _i12.GymService {
  @override
  _i7.Future<List<_i13.Gym>> fetchGymList() =>
      (super.noSuchMethod(
            Invocation.method(#fetchGymList, []),
            returnValue: _i7.Future<List<_i13.Gym>>.value(<_i13.Gym>[]),
            returnValueForMissingStub: _i7.Future<List<_i13.Gym>>.value(
              <_i13.Gym>[],
            ),
          )
          as _i7.Future<List<_i13.Gym>>);

  @override
  _i7.Future<String> addGym(_i13.Gym? gym) =>
      (super.noSuchMethod(
            Invocation.method(#addGym, [gym]),
            returnValue: _i7.Future<String>.value(
              _i14.dummyValue<String>(this, Invocation.method(#addGym, [gym])),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i14.dummyValue<String>(this, Invocation.method(#addGym, [gym])),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<void> updateGym(_i13.Gym? gym) =>
      (super.noSuchMethod(
            Invocation.method(#updateGym, [gym]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteGym(String? gymId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGym, [gymId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setActivity(_i13.Gym? gym) =>
      (super.noSuchMethod(
            Invocation.method(#setActivity, [gym]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteActivity(_i13.Gym? gym, _i15.Activity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#deleteActivity, [gym, activity]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String> uploadImage(String? base64Image) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [base64Image]),
            returnValue: _i7.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [base64Image]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [base64Image]),
              ),
            ),
          )
          as _i7.Future<String>);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i16.UserService {
  @override
  _i3.FirebaseAuth get firebaseAuth =>
      (super.noSuchMethod(
            Invocation.getter(#firebaseAuth),
            returnValue: _FakeFirebaseAuth_1(
              this,
              Invocation.getter(#firebaseAuth),
            ),
            returnValueForMissingStub: _FakeFirebaseAuth_1(
              this,
              Invocation.getter(#firebaseAuth),
            ),
          )
          as _i3.FirebaseAuth);

  @override
  set firebaseAuth(_i3.FirebaseAuth? _firebaseAuth) => super.noSuchMethod(
    Invocation.setter(#firebaseAuth, _firebaseAuth),
    returnValueForMissingStub: null,
  );

  @override
  _i2.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
            returnValueForMissingStub: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i2.FirebaseFirestore);

  @override
  set firestore(_i2.FirebaseFirestore? _firestore) => super.noSuchMethod(
    Invocation.setter(#firestore, _firestore),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i3.UserCredential?> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i7.Future<_i3.UserCredential?>.value(),
            returnValueForMissingStub: _i7.Future<_i3.UserCredential?>.value(),
          )
          as _i7.Future<_i3.UserCredential?>);

  @override
  _i7.Future<_i3.UserCredential?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i7.Future<_i3.UserCredential?>.value(),
            returnValueForMissingStub: _i7.Future<_i3.UserCredential?>.value(),
          )
          as _i7.Future<_i3.UserCredential?>);

  @override
  _i7.Future<_i3.UserCredential?> signUpWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailAndPassword, [email, password]),
            returnValue: _i7.Future<_i3.UserCredential?>.value(),
            returnValueForMissingStub: _i7.Future<_i3.UserCredential?>.value(),
          )
          as _i7.Future<_i3.UserCredential?>);

  @override
  _i7.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i17.User>> fetchUserList() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserList, []),
            returnValue: _i7.Future<List<_i17.User>>.value(<_i17.User>[]),
            returnValueForMissingStub: _i7.Future<List<_i17.User>>.value(
              <_i17.User>[],
            ),
          )
          as _i7.Future<List<_i17.User>>);

  @override
  _i7.Future<_i17.User?> fetchUser(_i3.User? firebaseUser) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUser, [firebaseUser]),
            returnValue: _i7.Future<_i17.User?>.value(),
            returnValueForMissingStub: _i7.Future<_i17.User?>.value(),
          )
          as _i7.Future<_i17.User?>);

  @override
  _i7.Future<void> createUser(_i17.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserFavourites(_i17.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserFavourites, [user]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i17.User>> fetchUsers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUsers, []),
            returnValue: _i7.Future<List<_i17.User>>.value(<_i17.User>[]),
            returnValueForMissingStub: _i7.Future<List<_i17.User>>.value(
              <_i17.User>[],
            ),
          )
          as _i7.Future<List<_i17.User>>);

  @override
  _i7.Future<void> updateUserProfile(_i17.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [user]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setSubscription(_i17.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#setSubscription, [user]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateMedicalCertificate(
    String? uid,
    DateTime? certificateExpDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMedicalCertificate, [
              uid,
              certificateExpDate,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeAccount(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [uid]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String> uploadImage(String? base64Image) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [base64Image]),
            returnValue: _i7.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [base64Image]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [base64Image]),
              ),
            ),
          )
          as _i7.Future<String>);
}

/// A class which mocks [InstructorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInstructorService extends _i1.Mock implements _i18.InstructorService {
  @override
  _i7.Future<List<_i19.Instructor>> fetchInstructors() =>
      (super.noSuchMethod(
            Invocation.method(#fetchInstructors, []),
            returnValue: _i7.Future<List<_i19.Instructor>>.value(
              <_i19.Instructor>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i19.Instructor>>.value(
              <_i19.Instructor>[],
            ),
          )
          as _i7.Future<List<_i19.Instructor>>);

  @override
  _i7.Future<_i19.Instructor?> fetchInstructorById(String? instructorId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchInstructorById, [instructorId]),
            returnValue: _i7.Future<_i19.Instructor?>.value(),
            returnValueForMissingStub: _i7.Future<_i19.Instructor?>.value(),
          )
          as _i7.Future<_i19.Instructor?>);

  @override
  _i7.Future<String?> addInstructor(_i19.Instructor? instructor) =>
      (super.noSuchMethod(
            Invocation.method(#addInstructor, [instructor]),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> deleteInstructor(_i19.Instructor? instructor) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInstructor, [instructor]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [SlotService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSlotService extends _i1.Mock implements _i20.SlotService {
  @override
  _i7.Future<List<_i9.Slot>> fetchUpcomingSlots(
    String? gymId,
    String? activityId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUpcomingSlots, [gymId, activityId, date]),
            returnValue: _i7.Future<List<_i9.Slot>>.value(<_i9.Slot>[]),
            returnValueForMissingStub: _i7.Future<List<_i9.Slot>>.value(
              <_i9.Slot>[],
            ),
          )
          as _i7.Future<List<_i9.Slot>>);

  @override
  _i7.Future<void> createSlot(_i9.Slot? slot) =>
      (super.noSuchMethod(
            Invocation.method(#createSlot, [slot]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateSlot(_i9.Slot? slot) =>
      (super.noSuchMethod(
            Invocation.method(#updateSlot, [slot]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteSlot(String? slotId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSlot, [slotId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i4.Client {
  @override
  _i7.Future<_i4.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i7.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i4.Response>);

  @override
  _i7.Future<_i4.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i7.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i4.Response>);

  @override
  _i7.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i21.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.Response>);

  @override
  _i7.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i21.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.Response>);

  @override
  _i7.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i21.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.Response>);

  @override
  _i7.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i21.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.Response>);

  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i7.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i22.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i7.Future<_i22.Uint8List>.value(_i22.Uint8List(0)),
            returnValueForMissingStub: _i7.Future<_i22.Uint8List>.value(
              _i22.Uint8List(0),
            ),
          )
          as _i7.Future<_i22.Uint8List>);

  @override
  _i7.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i7.Future<_i4.StreamedResponse>.value(
              _FakeStreamedResponse_3(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.StreamedResponse>.value(
              _FakeStreamedResponse_3(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i7.Future<_i4.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MapService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapService extends _i1.Mock implements _i23.MapService {
  @override
  _i7.Future<_i24.LocationPermission> checkLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkLocationPermission, []),
            returnValue: _i7.Future<_i24.LocationPermission>.value(
              _i24.LocationPermission.denied,
            ),
            returnValueForMissingStub:
                _i7.Future<_i24.LocationPermission>.value(
                  _i24.LocationPermission.denied,
                ),
          )
          as _i7.Future<_i24.LocationPermission>);

  @override
  _i7.Future<_i24.LocationPermission> requestLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocationPermission, []),
            returnValue: _i7.Future<_i24.LocationPermission>.value(
              _i24.LocationPermission.denied,
            ),
            returnValueForMissingStub:
                _i7.Future<_i24.LocationPermission>.value(
                  _i24.LocationPermission.denied,
                ),
          )
          as _i7.Future<_i24.LocationPermission>);

  @override
  _i7.Future<_i24.Position?> fetchUserLocation() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserLocation, []),
            returnValue: _i7.Future<_i24.Position?>.value(),
            returnValueForMissingStub: _i7.Future<_i24.Position?>.value(),
          )
          as _i7.Future<_i24.Position?>);

  @override
  _i7.Future<_i5.Locations> fetchGymLocations(List<_i13.Gym>? gymList) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGymLocations, [gymList]),
            returnValue: _i7.Future<_i5.Locations>.value(
              _FakeLocations_4(
                this,
                Invocation.method(#fetchGymLocations, [gymList]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Locations>.value(
              _FakeLocations_4(
                this,
                Invocation.method(#fetchGymLocations, [gymList]),
              ),
            ),
          )
          as _i7.Future<_i5.Locations>);
}
