// Mocks generated by Mockito 5.4.5 from annotations
// in dima_project/test/content/home/gym/activity/book_slot/slot_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dima_project/content/home/gym/activity/book_slot/slot_model.dart'
    as _i4;
import 'package:dima_project/content/home/gym/activity/book_slot/slot_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SlotService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSlotService extends _i1.Mock implements _i2.SlotService {
  MockSlotService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Slot>> fetchUpcomingSlots(
    String? gymId,
    String? activityId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUpcomingSlots, [gymId, activityId, date]),
            returnValue: _i3.Future<List<_i4.Slot>>.value(<_i4.Slot>[]),
          )
          as _i3.Future<List<_i4.Slot>>);

  @override
  _i3.Future<void> createSlot(_i4.Slot? slot) =>
      (super.noSuchMethod(
            Invocation.method(#createSlot, [slot]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
