// Mocks generated by Mockito 5.4.5 from annotations
// in dima_project/test/global_providers/user/user_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dima_project/global_providers/user/user_model.dart' as _i5;
import 'package:dima_project/global_providers/user/user_service.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserCredential?> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i3.Future<_i4.UserCredential?>.value(),
          )
          as _i3.Future<_i4.UserCredential?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.User?> fetchUser(_i4.User? firebaseUser) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUser, [firebaseUser]),
            returnValue: _i3.Future<_i5.User?>.value(),
          )
          as _i3.Future<_i5.User?>);

  @override
  _i3.Future<void> updateUserFavourites(_i5.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserFavourites, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.User>> fetchUsers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUsers, []),
            returnValue: _i3.Future<List<_i5.User>>.value(<_i5.User>[]),
          )
          as _i3.Future<List<_i5.User>>);
}
